student_rails/config/routes.rb
Rails.application.routes.draw do
  root "students#index"
  resources :students, only: %i[index show create update]
  resources :students do
    collection do
      post "delete_multiple", to: "students#delete_multiple"
    end
  end
  resources :labs, only: %i[index show create update destroy]
  resources :marks
end

student_rails/app/models/mark.rb
class Mark < ApplicationRecord
    belongs_to :student
    belongs_to :lab

    validates :grade, presence: true, inclusion: { in: [ "+", "++", "3", "4", "5" ] }
    validates :due_date, presence: true
    validates :comment, length: { maximum: 100 }
    validates :justification, length: { maximum: 1000 }

    validate :due_date_after_lab_date_of_issue
    validate :due_date_after_last_grade_date, on: :create

    before_save :mark_previous_final_grades_as_non_final

    private
    def due_date_after_lab_date_of_issue
        if lab.date_of_issue.present? && due_date < lab.date_of_issue
            errors.add(:due_date, "должна быть позже даты выдачи ЛР (#{lab.date_of_issue})")
        end
    end

    def due_date_after_last_grade_date
        last_grade = student.marks.where(lab: lab).order(due_date: :desc).first
        if last_grade&.due_date.present? && due_date <= last_grade.due_date
            errors.add(:due_date, "должна быть позже последней даты защиты (#{last_grade.due_date})")
        end
    end

    def mark_previous_final_grades_as_non_final
        if final?
            student.marks.where(lab: lab).update_all(final: false)
        end
    end
end

student_rails/app/controllers/marks_controller.rb
class MarksController < BaseController
  attr_accessor :page, :per_page, :total_pages, :query
  def index
    self.page = (params[:page] || 1).to_i
    self.per_page = 10

    self.query = Student.all

    self.entities = query.offset((self.page - 1) * self.per_page).limit(self.per_page)
    self.total_pages = (query.count / self.per_page.to_f).ceil
    self.total_pages = 1 if self.total_pages == 0
  end
end

student_rails/app/views/marks/_edit_contact_modal.html.erb
<div id="edit-contact-modal" class="modal fade" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Редактировать Контакты</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="edit-contact-form">
                    <div class="mb-3">
                        <label for="telegram-value" class="form-label">Telegram</label>
                        <input type="url" class="form-control" id="telegram-value" name="telegram_value" placeholder="Telegram">
                    </div>
                    <div class="mb-3">
                        <label for="email-value" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email-value" name="git_value" placeholder="Email">
                    </div>
                    <div class="mb-3">
                        <label for="phone_number-value" class="form-label">Телефон</label>
                        <input type="text" class="form-control" id="phone-value" name="phone_number_value" placeholder="Телефон">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                <button type="button" class="btn btn-primary" id="save-contact-button">Сохранить</button>
            </div>
        </div>
    </div>
</div>

student_rails/app/views/marks/_edit_git_modal.html.erb
<div id="edit-git-modal" class="modal fade" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Редактировать Git</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="edit-git-form">
                    <div class="mb-3">
                        <label for="git-value" class="form-label">Git</label>
                        <input type="url" class="form-control" id="git-value" name="git_value" placeholder="Git" required>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                <button type="button" class="btn btn-primary" id="save-git-button">Сохранить</button>
            </div>
        </div>
    </div>
</div>

student_rails/app/views/marks/index.html.erb
<div class="container mt-5">
  <%= form_with url: students_path, method: :get, local: true, class: 'mb-4' do |f| %>
    <div class="row">
      <div class="col-md-3 mb-3">
        <%= f.label :full_name, "Фамилия и инициалы" %>
        <%= f.text_field :full_name, class: 'form-control', placeholder: "Фамилия и инициалы", value: params[:full_name] %>
      </div>

      <div class="col-md-3 mb-3">
        <%= f.label :git, "Git" %>
        <%= f.select :git, options_for_select([['Да', 'yes'], ['Нет', 'no']], params[:git]), { include_blank: 'Не важно' }, { class: 'form-control', id: 'git-select' } %>
        <%= f.text_field :git_value, class: 'form-control mt-2', placeholder: "Git", id: 'git-text-field', value: params[:git_value], disabled: params[:git] != 'yes' %>
      </div>

      <div class="col-md-3 mb-3">
        <%= f.label :email, "Email" %>
        <%= f.select :email, options_for_select([['Да', 'yes'], ['Нет', 'no']], params[:email]), { include_blank: 'Не важно' }, { class: 'form-control', id: 'email-select' } %>
        <%= f.text_field :email_value, class: 'form-control mt-2', placeholder: "Email", id: 'email-text-field', value: params[:email_value], disabled: params[:email] != 'yes' %>
      </div>

      <div class="col-md-3 mb-3">
        <%= f.label :phone, "Номер телефона" %>
        <%= f.select :phone, options_for_select([['Да', 'yes'], ['Нет', 'no']], params[:phone]), { include_blank: 'Не важно' }, { class: 'form-control', id: 'phone-select' } %>
        <%= f.text_field :phone_value, class: 'form-control mt-2', placeholder: "Номер телефона", id: 'phone-text-field', value: params[:phone_value], disabled: params[:phone] != 'yes' %>
      </div>

      <div class="col-md-3 mb-3">
        <%= f.label :telegram, "Telegram" %>
        <%= f.select :telegram, options_for_select([['Да', 'yes'], ['Нет', 'no']], params[:telegram]), { include_blank: 'Не важно' }, { class: 'form-control', id: 'telegram-select' } %>
        <%= f.text_field :telegram_value, class: 'form-control mt-2', placeholder: "Telegram", id: 'telegram-text-field', value: params[:telegram_value], disabled: params[:telegram] != 'yes' %>
      </div>

      <div class="col-md-3 mb-3">
        <%= link_to 'Сбросить фильтры', students_path, class: 'btn btn-danger', style: 'margin-top: 30px;' %>
      </div>
    </div>
  <% end %>

  <table class="table table-bordered">
    <thead class="table-light">
      <tr>
        <th></th>
        <th>№</th>
        <th>
          <%= link_to 'Полное имя', class: 'sortable', data: { column: 'first_name' } do %>
            <span>Полное имя</span>
          <% end %>
        </th>
        <th>
          <%= link_to 'Git', class: 'sortable', data: { column: 'git' } do %>
            <span>Git</span>
          <% end %>
        </th>
        <th>
          <%= link_to 'Контакт', class: 'sortable', data: { column: 'contact' } do %>
            <span>Контакт</span>
          <% end %>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @entities.each_with_index do |student, index| %>
        <tr class="<%= 'table-danger' unless student.validate? %>">
          <td>
            <input type="checkbox" class="student-checkbox" data-id="<%= student.id %>">
          </td>
          <td><%= (@page - 1) * @per_page + index + 1 %></td>
          <td><%= student.get_full_name %></td>
          <td><%= student.git %></td>
          <td><%= student.get_any_contact %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="mt-3 d-flex justify-content-between align-items-center">
    <div class="d-flex align-items-center">
      <% if @page > 1 %>
        <%= link_to '<', students_path(page: @page - 1, full_name: params[:full_name], git: params[:git], email: params[:email], phone: params[:phone], telegram: params[:telegram], sort_column: params[:sort_column], sort_order: params[:sort_order]), class: 'btn btn-secondary' %>
      <% else %>
        <button class="btn btn-secondary disabled"><</button>
      <% end %>

      <span class="mx-3">Страница <%= @page %> из <%= @total_pages %></span>

      <% if @page < @total_pages %>
        <%= link_to '>', students_path(page: @page + 1, full_name: params[:full_name], git: params[:git], email: params[:email], phone: params[:phone], telegram: params[:telegram], sort_column: params[:sort_column], sort_order: params[:sort_order]), class: 'btn btn-secondary' %>
      <% else %>
        <button class="btn btn-secondary disabled">></button>
      <% end %>
    </div>
  </div>

  <div class="d-flex justify-content-between mt-3">
    <button id="add-mark-btn" class="btn btn-success">Добавить оценку</button>
    <button id="change-mark-btn" class="btn btn-warning">Изменить последнюю оценку</button>
    <button id="delete-mark-btn" class="btn btn-danger">Удалить последнюю оценку</button>
    <button id="history-btn" class="btn btn-info">Просмотреть историю</button>
    <button id="edit-git-btn" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#edit-git-modal">Изменить Git</button>
    <button id="edit-contact-btn" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#edit-contact-modal">Изменить контакты</button>
    <button id="update-marks-btn" class="btn btn-info">Обновить</button>
  </div>
</div>

<%= render 'edit_git_modal' =%>
<%= render 'edit_contact_modal' %>

<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>